sonar.sources=.
sonar.tests=tests,e2e
sonar.test.inclusions=tests/**/*.js,e2e/**/*.js
sonar.exclusions=node_modules/**,**/*.min.js,scripts/**,e2e/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=content.js,popup.js,content.css,popup.css,**/*.html
